spring:
  application:
    name: leag-of-legends-ia
  datasource:
    url: jdbc:h2:mem:lolia
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true